apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dbdata
  name: dbdata2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Mi
status: {}
