apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-data-dev
  name: db-data-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Mi
status: {}
